spring.application.name=brandbeacon

# \uC11C\uBC84 \uD3EC\uD2B8 \uC124\uC815
server.port=8089
# \uBAA8\uB4E0 \uB124\uD2B8\uC6CC\uD06C\uC5D0\uC11C \uC694\uCCAD\uC744 \uBC1B\uACA0\uB2E4, (\uB85C\uCEEC, \uC678\uBD80, \uB3C4\uCEE4...)
server.address=0.0.0.0

# ${} : \uBBFC\uAC10\uD55C \uB0B4\uC6A9\uC744 \uD658\uACBD \uBCC0\uC218\uB85C \uAC00\uC838\uC624\uACA0\uB2E4\uB294 \uC758\uBBF8
# -> \uBCC0\uC218 \uC5EC\uB7EC\uAC1C \uC0AC\uC6A9\uD558\uAE30 \uB54C\uBB38\uC5D0 \uAD04\uD638 \uC548\uC5D0 \uAD6C\uBD84\uD558\uB294 \uB0B4\uC6A9 \uC368\uC918\uC57C\uD568!
# DB(MySQL)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_SCHEMA}?serverTimezone=Asia/Seoul
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA \uC124\uC815
# JPA : SQL\uC744 \uC790\uB3D9\uC73C\uB85C \uC0DD\uC131\uD558\uACE0 \uAD00\uB9AC\uD574\uC8FC\uB294 \uAE30\uC220
# ddl-auto : \uD14C\uC774\uBE14\uC744 \uC790\uB3D9\uC73C\uB85C \uC0DD\uC131 / \uC218\uC815\uD558\uB294 \uC124\uC815
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MySQL dialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Thymeleaf
# cache = false -> \uC218\uC815\uC0AC\uD56D\uC744 \uBC14\uB85C \uBC18\uC601\uD558\uAE30 \uC704\uD574 \uC0AC\uC6A9
# cache : \uC11C\uBC84 \uC131\uB2A5 \uD5A5\uC0C1\uC744 \uC704\uD574 \uC0AC\uC6A9\uD558\uC9C0\uB9CC, \uAC1C\uBC1C \uD658\uACBD\uC5D0\uC11C\uB294 \uB044\uB294 \uAC83\uC774 \uC88B\uC74C
spring.thymeleaf.cache=false

# \uAD6C\uAE00 OAuth2 \uB85C\uADF8\uC778 \uC124\uC815
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email, profile